inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3
Metrics/LineLength:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StderrPuts:
  Enabled: false
